[package]
name = "pallet-mq-runtime-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", default-features = false }
phala-mq = { path = "../../../crates/phala-mq", default-features = false }

[features]
default = ["std"]
std = [
	"sp-api/std",
]
