[package]
name = "sgx-attestation"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], default-features = false }
pink-json = { version = "0.4", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }

# Release version no-std has bug
webpki = { git = "https://github.com/rustls/webpki", version = "0.102.0-alpha.3", package = "rustls-webpki", default-features = false, features = ["alloc", "ring"] }

[dev-dependencies]
insta = "1"

[features]
default = ["std"]
std = ["pink-json/std", "serde/std"]
